# Generated by Django 5.1.4 on 2024-12-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "db_table": "currencies",
            },
        ),
        migrations.CreateModel(
            name="CurrencyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=50, unique=True)),
                ("total_buys", models.FloatField(default=0)),
                ("average_buy_price", models.FloatField(default=0)),
                ("total_sells", models.FloatField(default=0)),
                ("average_sell_price", models.FloatField(default=0)),
                ("profit", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("total", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "type",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")],
                        default="buy",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("password", models.IntegerField()),
            ],
        ),
    ]
