# Generated by Django 5.1.4 on 2024-12-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_and_trades", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currency",
            name="price",
        ),
        migrations.AddField(
            model_name="currency",
            name="buy_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="currency",
            name="sell_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
