# Generated by Django 5.1.4 on 2025-01-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_and_trades", "0002_remove_currency_price_currency_buy_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="currencyreport",
            name="total_buy_amount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="currencyreport",
            name="total_sell_amount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="currencyreport",
            name="currency",
            field=models.CharField(max_length=10),
        ),
    ]
